# Numpy

In [ ]:
import numpy as np

In [ ]:
import numpy as np
array = np.array([[2,4,5],
                 [76,34,12],
                 [2,0,65]])
print(array)

In [ ]:
import numpy as np
array = array = np.array([[["A","B","C"], ["D","E","F"], ["G","H","I"]],
                           [["J","K","L"], ["M","N","O"], ["P","Q","R"]],
                           [["S","T","U"], ["V","W","X"], ["Y","Z"," "]]])
print(array.shape)        #OUTPUT:  (layers, no_of_rows, no_of_columns)

Multidimensional Indexing

In [ ]:
import numpy as np
array = array = np.array([[["A","B","C"], ["D","E","F"], ["G","H","I"]],
                           [["J","K","L"], ["M","N","O"], ["P","Q","R"]],
                           [["S","T","U"], ["V","W","X"], ["Y","Z"," "]]])
print(array[0,0,2])

### Slicing

 Note:- array [ start : stop : step ]

In [ ]:
import numpy as np
array = array = np.array([[["A","B","C"], ["D","E","F"], ["G","H","I"]],
                           [["J","K","L"], ["M","N","O"], ["P","Q","R"]],
                           [["S","T","U"], ["V","W","X"], ["Y","Z"," "]]])
print(array[0])
print()
print(array[-1])
print()
print(array[0:1:])

In a 2D array  it looks like this array[ row, column, step ]

- last element

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
#
print(array[-1])
print()
print(array[0:2])

- Print from start up until the very end

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[0:])

- Selecting all rows and print with step2

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[::2])

- Printing all rows in reverse order

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[::-1])

- For Every row and its 1st column 

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:,1])

- Second last column

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:,-2])

- First 3 columns of every row    ->  [ row = :, column= required range]

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:, 0:3])

- For all rows, skip first column and print till end column

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:, 1:])

- For Every second Column

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:, ::2])

- Every Second Column, but start at column 1

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:, 1::2])

- To print every column but in reverse order

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:, ::-1])

- Both row and column selection

 First two column of the first two rows

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[0:2, 0:2])

 From the second column to the last column of the first two row

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[0:2, 2:])

First two Columns of last two Rows

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[2:, 0:2])

Last two rows and Last two columns

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[2:, 2:])

In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:2:1])

### Arithmetic

i) Scalar Arithmetic

In [ ]:
import numpy as np
array=np.array([1, 2, 3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

ii) Vectorized Math Functions

In [ ]:
import numpy as np
array=np.array([1, 2, 3])

print(np.sqrt(array))

In [ ]:
import numpy as np
array=np.array([1.01, 2.5, 3.99])   

print(np.round(array))
print(np.floor(array))  #always round down
print(np.ceil(array))   #always round up

returns pi value

In [ ]:
import numpy as np
print(np.pi)

In [ ]:
import numpy as np
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

iii) Element-Wise Arithmetic

In [ ]:
import numpy as np

array1=np.array([1, 2, 3])
array2=np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

iv) Comparison Operators

In [ ]:
import numpy as np

scores = np.array([91, 34, 55, 67, 23, 78])

print(scores >= 60)

# If score is less than 60, assign them zero
scores[scores < 60] = 0
print(scores)

### Broadcasting

- It allows Numpy to perform operations on arrays with different shapes by virtually expanding dimensions. so, they  match the larger array's shape.
- The dimension have the same size OR One of the dimensions have a size of 1

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,  10])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

### Aggregate

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array))

print(np.mean(array))

print(np.std(array))

print(np.var(array))

print(np.min(array))

print(np.max(array))

print(np.argmin(array))

print(np.argmax(array))

print(np.sum(array, axis=0))

print(np.sum(array, axis=1))

### Filtering

In [9]:
import numpy as np

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >= 65]
even = ages[ages % 2 == 0]
odds = ages[ages % 2 !=0]

print(teenagers)
print(adults)
print(seniors)
print(even)
print(odds)


[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


- Access the Numpy

Syntax: np.where(condition, value_if_true, value_if_false)

In [10]:
import numpy as np

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

adults = np.where(ages >= 18, ages, 0)
print(adults)



[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


### Random Numbers

syntax:  rng = np.random.default_rng()
         rng.integers(low, high, size)

In [ ]:
import numpy as np
rng = np.random.default_rng()

print(rng.integers(low=1, high=9))

8


If you want the size of n ie there should be n random integers every time

In [ ]:
import numpy as np
rng = np.random.default_rng()

print(rng.integers(low=1, high=9, size=2))

[3 4]


If you want random number with specific rows and columns

In [23]:
import numpy as np
rng = np.random.default_rng()

print(rng.integers(low=1, high=9, size=(3,2)))

[[5 8]
 [7 5]
 [2 5]]


If you want that exact same random number every time, then use a 'seed' inside the 'default_rng()'

In [26]:
import numpy as np
rng = np.random.default_rng(seed=1)

print(rng.integers(low=1, high=9, size=(3,2)))

[[4 5]
 [7 8]
 [1 2]]


If you want every value has uniform has equal chance of being selected

In [ ]:
import numpy as np

print(np.random.uniform())

# If you want a range like -1 to 1 

np.random.seed(seed=1)     #Add seed if you want same value

print(np.random.uniform(low=-1, high=1, size=(3,2)))

0.1862602113776709
[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


To shuffle an Array:

In [42]:
import numpy as np

rng = np.random.default_rng()

array = np.array([1, 2, 3, 4, 5])

rng.shuffle(array)

print(array)

[3 5 1 4 2]


Random choice

In [41]:
import numpy as np

rng = np.random.default_rng()

fruits = np.array(["apple", "orange", "banana", "coconut", "pineapple"])
fruits = rng.choice(fruits, size=(3, 3))
print(fruits)


[['pineapple' 'apple' 'coconut']
 ['pineapple' 'banana' 'apple']
 ['pineapple' 'pineapple' 'pineapple']]
